# Site settings
author: Dwight Marie
title: 
header-img: img/home-bg.png
email: dwightmarie@gmail.com
copyright_name: Dwight Marie
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: brownhumor
github_username:  Deemarie7154

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
